FROM python:2.7-onbuild

COPY . /usr/src/app/

ENTRYPOINT ["python", "-u", "pyroAdapter.py" , "--bname=Agent", "--bpath=C:\\Users\\Farshid\\Desktop\\thesis\\early-fault-dete
ction\\training\\agent\\agent.p", "--ns"]
